name: "Say Hello"
description: "Say Hello to the world"
author: "Shahal Thayyil"
inputs:
  name:
    description: "Name of the person to say hello to"
    required: false
    default: "World"

runs:
  using: "composite"
  steps:
    - name: "Say Hello"
      run: |
        echo "Hello, ${{ inputs.name }}!"
    - name: "Say Goodbye"
      run: ./hello.sh "${{ inputs.name }}"
      shell: bash
      